
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"  # Remove in production
    volumes:
      - db_data:/Users/preethamarmoor/Projects/pyapp/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init script (optional)
  app:
    build: ./app  # Specify the build context
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app  # Mount the app directory
    command: python app.py

volumes:
  db_data:
    driver: local  # Choose a volume driver if needed (e.g., local, nfs)