version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      DATABASE_URL: postgres://postgres:postgres@db:5432/test
    ports:
      - "5432:5432" # Remove in production
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init script (optional)
  app:
    build: ./app # Specify the build context
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app # Mount the app directory
    command: python appy.py

volumes:
  db_data:
    #driver:local